site_name: Roar User Guide
site_url: https://docs.icds.psu.edu
site_description: User documentation for the Roar Supercomputer hosted by the Institute of Computational and Data Sciences at the Pennsylvania State University.
site_author: Institute of Computational and Data Sciences
#repo_url: https://github.com/PSU-ICDS/icds_docs
#edit_url: edit/staging/docs/

theme: 
  name: readthedocs
#  features:
#    - content.code.copy
#    - navigation.sections
#    - navigation.footer
  highlightjs: false
  logo: img/PSU_ICDS_logo_blue.png
  site_favicon: img/favicon.ico
  next_previous: true
#extra:
#  generator: false
#extra_footer: |
#  [Contribute to this project](https://github.com/PSU-ICDS/icds_docs/CONTRIBUTING.md)


extra_css: 
    - css/extra.css

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

plugins:
#    - bootstrap4-blockquotes
#    - bootstrap4-tables

nav:
    - Getting started: 
        - getting-started/system-overview.md
        - getting-started/compute-hardware.md
        - getting-started/tips-for-beginners.md
        - getting-started/connecting.md
    - Accounts:
        - accounts/paying-for-compute.md
        - accounts/managing-accounts.md
    - File system:
        - file-system/file-storage.md
        - file-system/managing-files.md
        - file-system/finding-files.md
        - file-system/transferring-files.md
    - Software:
        - software/modules.md
        - software/installing-from-source.md
        - software/custom-modules.md
        - software/containers.md
    - Packages: 
        - packages/python.md
        - packages/r-libraries.md
        - packages/anaconda.md
    - Running Jobs:
        - running-jobs/portal.md
        - running-jobs/slurm-scheduler.md
        - running-jobs/interactive-jobs.md
        - running-jobs/batch-jobs.md
        - running-jobs/hardware-requests.md
    - Roar restricted:
        - roar-restricted/accessing-rr.md
        - roar-restricted/data-transfer.md
             
