site_name: Roar User Guide
site_url: https://docs.icds.psu.edu
site_description: User documentation for the Roar Supercomputer hosted by the Institute of Computational and Data Sciences at the Pennsylvania State University.
site_author: Institute of Computational and Data Sciences
#repo_url: https://github.com/PSU-ICDS/icds_docs
#edit_url: edit/staging/docs/

theme: 
  name: readthedocs
#  features:
#    - content.code.copy
#    - navigation.sections
#    - navigation.footer
  highlightjs: false
  logo: img/PSU_ICDS_logo_blue.png
  site_favicon: img/favicon.ico
  next_previous: true
#extra:
#  generator: false
#extra_footer: |
#  [Contribute to this project](https://github.com/PSU-ICDS/icds_docs/CONTRIBUTING.md)


extra_css: 
    - css/extra.css

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

plugins:
#    - bootstrap4-blockquotes
#    - bootstrap4-tables

nav:
    - Getting started: 
        - getting-started/system-overview.md
        - getting-started/before-you-start.md
        - getting-started/compute-hardware.md
        - getting-started/connecting-to-rc.md
    - File system:
        - handling-files/file-storage.md
        - handling-files/managing-files.md
        - handling-files/searching-files.md
        - handling-files/transferring-files.md
    - Accounts:
        - accounts/accounts.md
        - accounts/managing-accounts.md
    - Software:
        - software/modules.md
        - software/installing-from-source.md
        - software/custom-modules.md
        - software/using-containers.md
    - Packages: 
        - packages/packages.md
        - packages/r.md
        - packages/anaconda.md
    - Running Jobs:
        - running-jobs/portal.md
        - running-jobs/slurm.md
        - running-jobs/interactive-jobs.md
        - running-jobs/batch-jobs.md
        - running-jobs/hardware-requests.md
    - Roar restricted:
        - restricted/rr-getting-started.md
        - restricted/rr-handling-data.md
             
